export const JOBS = [
    {
        company: 'Loud Intelligence',
        color: 'blue-talenthackers',
        url: 'https://loudintelligence.com/',
        logoUrl: '/jobs/loudintelligence-logo.png',
        imgUrl: '/jobs/loudintelligence.webp',
        position: 'Front-end Engineer',
        from: 'Feb 2024',
        to: 'Present',
        description: ' I contribute to the development of the Voi<3 platform, focusing on creating intuitive and engaging user interfaces for generating audio ad campaigns. My role involves collaborating with a cross-functional team to ensure seamless user experiences and bring innovative features to life.',
        skills: ['react', 'next', 'js'],
    },
    {
        company: 'TalentHackers',
        color: 'blue-talenthackers',
        url: 'https://talenthackers.net/',
        logoUrl: '/jobs/talenthackers-logo.webp',
        logoDarkUrl: '/jobs/talenthackers-logo-dark.webp',
        imgUrl: '/jobs/talenthackers.webp',
        position: 'Front-end Engineer',
        from: 'Feb 2023',
        to: 'Present',
        description: 'I developed and updated solutions for the IT talent acquisition area. Implemented best practices and refactors to enhance code quality and user experience.',
        skills: ['vue', 'nuxt', 'js'],
    },
    {
        company: 'Coderhouse',
        color: 'black',
        url: 'https://coderhouse.com/',
        logoUrl: '/jobs/coderhouse-logo.png',
        imgUrl: '/jobs/coderhouse.svg',
        position: 'JS Mentor',
        from: 'Jun 2022',
        to: 'Jun 2024',
        description: 'I guided and mentored over a thousand students in their introduction to programming with JavaScript, from foundational concepts to the completion of a comprehensive final project. My efforts were consistently recognized with multiple accolades, highlighting my dedication and effectiveness as a mentor.',
        skills: ['js'],
    },
    {
        company: '9net',
        color: 'red-9net',
        url: 'https://www.9net.com.ar',
        logoUrl: '/jobs/9net-logo.svg',
        imgUrl: '/jobs/9net.svg',
        position: 'Fullstack Engineer',
        from: 'Oct 2018',
        to: 'Oct 2020',
        description: 'I contributed to the migration and modernization of a comprehensive management system, transitioning from PHP with Twig views to Laravel and Vue 2. I implemented new tools for the Biblioteca del Congreso de La Nación (National Congress Library) and the Municipio de San Fernando (Municipality of San Fernando), including an entry system for the Library and a strategic dashboard for the Municipality.',
        skills: ['vue', 'js', 'php'],
    }
]
